name: {{name}}
description: Implementation of {{name}} feature
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  common: 0.0.1
  {{name}}_api: 0.0.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.9.1
  build_runner: ^2.10.5
  freezed: ^3.2.3

flutter:
  generate: true
