name: login
description: Login feature
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.18.0-18.0.pre.54"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  common_dependencies: 0.0.1
  core: 0.0.1
  authentication: 0.0.1
  network: 0.0.1
  simple_animations: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true