name: common_dependencies
description: This package aims to provide common dependencies between modules
publish_to: none
version: 0.0.1

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=3.18.0-18.0.pre.54"

dependencies:
  flutter:
    sdk: flutter

  #路由导航
  navigator: 0.0.1
  #鉴权
  authentication: 0.0.1
  ## Packages
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  package_info_plus: ^8.1.2
  dio: ^5.7.0
  #数据比较
  equatable: ^2.0.7
  #输入校验
  formz: ^0.8.0
  #数据存储
  shared_preferences: ^2.3.4
  # widget管理
  flutter_hooks: ^0.20.5
  hooked_bloc: ^1.5.0
  bloc: ^8.1.4
  #toast
  fluttertoast: ^8.2.10
  #路由
  go_router: ^14.6.2
  path: ^1.9.0
dev_dependencies:
  flutter_test:
    sdk: flutter

